- service.go
Aiven now returns <service-name>.<project>.aivencloud.com:<port> as the URI. According to this documentation, https://golang.org/pkg/net/url/#URL, only scheme and opaque will be filled in this scenario.
> Fix issue with URI not being able to be parsed properly

- kafka_topic.go
The field was defined as string but the API specs define it as int and optional: https://api.aiven.io/doc/#api-Service__Kafka-ServiceKafkaTopicUpdate
> min_insync_replicas as int field (according to Aiven API specs)

- service.go
@jelmersnoeck [Adds basic `user_config` to the service definition](https://api.aiven.io/doc/#api-Service-ServiceCreate) so that users can pass through additional database configuration. I abstained for now from adding checks b/c the aiven API will return errors on bad/unknown fields.
> Adds basic user-config field to service

- service.go
@jelmersnoeck @FranOis 
Needed to add a `ConnectionInfo` struct so the terraform provider can output data on specific kafka details. Some of this stuff is important for downstream deployments, eg -- what is my kafka connect URL? What is the access cert/key for kafka?
> Add connection details to service object

- ca.go
- client.go
@FranOis @jelmersnoeck 
Morning guys, this adds a feature to the project component so that we fetch CA Certificates when we grab project information. This will be useful for some of the Aiven clients that use TLS, since the CA will need to be specified so that users dont have to use insecure connections/blindly trust.
> Fetch Project CA along with Project details

- service.go
- service_integration.go
Some integrations must be defined as part of service creation for them
to work correctly.
> Allow defining service integrations when creating a new service

- service.go
In the API, when making an API call to get a service, or list services for a project the service integrations are returned for a given service, in the JSON response, under the key `service_integrations`.
The service integrations are currently present in the response, but not in the struct returned by `client.Services.List` or `client.Services.Get`.
I've chosen to call it `Integrations` even though the key name in the API response is `service_integrations` because `Integrations` is consistent with `service_uri` ➡️ `URI`
> Add service integrations to service

- auth.go
- client.go
MFAUserToken and doRequest functions were doing pretty much the same, calling API using an HTTP client
> Unify http client usage

- kafka_connector.go
Kafka Connectors response representation in code does not match the actual API JSON response. `KafkaConnectorTask.Connectors.Tasks.Task `is a number in API JSON Response but has the string type in the code.
> Kafka connector response Task type fixed

- kafka_schemas.go
- kafka_schemas_test.go
Aiven API Kafka Schema Global configuration GET and PUT methods have different response signatures. Get method retrieves ```{"compatibilityLevel":"FULL"}``` and PUT method expect and retrieves back ```{"compatibility":"FULL"}``` **compatibility** not **compatibilityLevel**
> Kafka schema global configuration PUT request changes

- accounts_acc_test.go
- project.go
- project_acc_test.go
- Account Id property should be optional and omitted if empty, API expects this behaviour, otherwise impossible to create new projects since it tries to link a project with an empty account. 
- Also, in the new version of Aiven API name for the account and team account should be alphanumeric and do not support special symbols.
> Fix project account

- aiven_go_client_suite_test.go
- mirrormaker_replication_flow_acc_test.go
Use an existing project for acceptance test instead of creating a new one each time during the run.
> acceptance tests use an existing project

- project_user.go
API retrieves a list of all project users, including account team members, when a team is associated with the project. Unfortunately, this makes a get method unreliable when a project user and account team member has the same email address. Therefore we filter out all account team members from the list by checking team_id fields. Account team members do have a separate API endpoint and can be excluded from project users search.
> fix project user get method

- project.go
- project_acc_test.go
I need to be able to get the event logs for a given project ref: https://api.aiven.io/doc/#operation/ProjectGetEventLogs.
> Add method on ProjectsHandler to get event logs

- service_user.go
This PR adds missing field to the ModifyServiceUserRequest, allowing to update Redis user AccessControl.
> Add AccessControl to ModifyServiceUserRequest

- service_user.go
Not omitting NewPassword field prevent from just updating the access control on users
> Fix ModifyServiceUserRequest fields should be omitted if empty

- service_user.go
When updating the AccessControl of a redis user and empty fields are not omitted we get a 400 error from aiven API.
Sorry for the multiple PRs.
> Fix AccessControl struct fields should be omitted if empty

- connection_pool.go
This is currently a required field on the request structs while the API
does not require it.  Omitting it results in the pool using the
'Reuse inbound user', like the UI defaults to.
> Make username an optional field on ConnectionPool requests

- azure_privatelink.go
Adds ability to refresh an Azure privatelink and manage connections of a privatelink. Useful for automating end-to-end bringup of azure privatelinks on a service (terraform changes to follow)
> Add support for managing Azure privatelink connections

- service_user.go
This PR is to adds the m3_group on the service user.
I did not set omitempty on it since if we want to delete the group, we need to explicitly set a null on it. Tried with a curl on a PG service, looks like the explicit null does not break the update a user on other engines.
> adds the m3_group in the service_user.access_control struct

- client.go
Fixes a small oversight that results in a crash when accessing the clickhouse query api
> clickhouse_query: add forgotten attribute

- .gitignore
- billing_group.go
- billing_group_acc_test.go
Allow creating a new billing group by copying the data from an existing one.
> Add support to create billing group by copying from an existing one

- service_integration.go
user_config field is actually required by API https://api.aiven.io/doc/#operation/ServiceIntegrationUpdate
> make UpdateServiceIntegrationRequest.UserConfig required

- account_authentications.go
- account_authentications_test.go
- accounts_acc_test.go
- kafka_connector.go
Currently AccountAuthenticationMethod struct has all available fields for request and response objects for all http methods. 
Some fields do not support update: authentication_method_id, authentication_method_type. They should not be sent by client because serves does not expect additional fields. 
Some fields do not exist in update response (at least).
https://api.aiven.io/doc/#operation/AccountAuthenticationMethodUpdate
This request adds separate structs for update method request and response.
> fix AccountAuthenticationUpdate method

- go.mod
- go.sum
- vpc.go
- vpc_peering_connection.go
- vpc_peering_connection_test.go
peerResourceGroup is [optional](https://github.com/aiven/aiven-client/blob/e48db8a3ebdac4af66acd995e324d5c56434828a/aiven/client/client.py#L1284) and acts as additional filter
> fix GetVPCPeeringWithResourceGroup, set peerResourceGroup optional

- project.go
- makes `add_account_owners_admin_access` optional for [create](https://api.aiven.io/doc/#operation/ProjectCreate)
- adds `add_account_owners_admin_access` to project [update request](https://api.aiven.io/doc/#operation/ProjectUpdate)
> fix project create/update

- client.go
- go.mod
- go.sum
Uses https://github.com/hashicorp/go-retryablehttp as a client
> use go-retryablehttp as a client

- .github/workflows/releaser.yml
adds releaser which is to automatically create releases, similarly as in https://github.com/aiven/go-api-schemas
> ci: add releaser

- clickhouse_query.go
- clickhouse_user.go
- Handle Clikhouse current queries API
- Clickhouse reset password API return a json with the field "password" but client tried to unmarshal in go struct with the json tag "name", so the client didn't return the new password. Fixed by replacing json tag.
> feat(clickhouse): current queries handler

- examples/accounts/main.go
- examples/elasticsearch/main.go
- examples/kafka_connectors/main.go
- examples/kafka_schemas/main.go
- go.mod
currently, it's not possible to install `aiven-go-client` v2 as a dependency because of the following error:
```log
go: github.com/aiven/aiven-go-client@v2.0.0-rc.4: invalid version: module contains a go.mod file, so module path must match major version ("github.com/aiven/aiven-go-client/v2")
```
this PR addresses this issue, see https://donatstudios.com/Go-v2-Modules for more information
> chore: compatibility as a go mod dependency

- client.go
- opensearch_acls.go
- opensearch_acls_test.go
> feat(opensearch): implement support for opensearch acls

- mirrormaker_replication_flow.go
fixes missing `omitempty` in replication flow
> fix(mirrormaker): missing omitempty in replication flow

- kafka_topic.go
temporarily disables `local_retention_*` fields in `kafkatopic` as a hotfix
> fix(kafkatopic): temporarily disable local_retention_* fields

- kafka_topic.go
> fix(kafka_topic): config to read

- project.go
Hello,
We're manipulating the projects events and we've seen the id is missing in the SDK compared to the API declaration.
cf: https://api.aiven.io/doc/#tag/Project/operation/ProjectGetEventLogs
Cheers
> fix(projectEvents): add missing id

- .github/workflows/releaser.yml
> ci: update version.go in releaser github workflow

- client.go
Adds a fixed `User-Agent` for telemetry purposes.
> feat(client): user-agent telemetry

- service.go
Adds Thanos support in `ConnectionInfo` struct under `service.go`.
> feat(service/connectioninfo): thanos support

- mirrormaker_replication_flow.go
Adds ReplicationFlow `config_properties_exclude`
> feat: add `config_properties_exclude` to mirrormaker ReplicationFlow

- clickhouse_user.go
When the password sent as nil, it is generated on the BE.
We shouldn't invent a wheel and generate passwords on client side if that's not a case.
> fix: generate clickhouse user password on be

- kafka_topic.go
- kafka_topic_acc_test.go
Make it possible to provide topic_description and owner_user_group_id when creating and updating topic. Also adds it to the schema.
> feat: Add support for description and owner for topics

- service.go
[ServiceGet](https://api.aiven.io/doc/#tag/Service/operation/ServiceGet) response doesn't contain powered. Previously, the field defaulted to `false`.
To verify the service state, use the `State` field. When the service is powered off, state is "POWEROFF".
> fix: remove `Powered` field from from `Service` type (#365)
