kafka_topic.go

remove unneeded io/util

---

service.go

@jelmersnoeck @FranOis I made an oversight on the `user_config` feature -- [needs to be added for Updates as well](https://api.aiven.io/doc/#api-Service-ServiceUpdate).

Adds user_config to service update

---

client.go

v1 api is available as of today, start using it.

api version: switch to v1

---

Makefile
client.go
errors.go
internal/testhelpers/client.go
kafka_acl.go

Retrying GET requests is safe and in case of certain error codes there's
a good chance retrying will return a different result.

client: Retry GET requests in certain error cases

---

.gitignore
.travis.yml

- Added make test and make lint to CI
- updates .gitignore

small improvements

---

kafka_schemas.go
kafka_schemas_test.go

Extend a list of supported Kafka Schemas responses

kafka schemas: extend a list of supported responses

---

ca.go
card.go
client.go
connection_pool.go
database.go
errors.go
project.go

Updated some of the comments which are visible in the generated documentation for the client-project.

godoc: Minor documentation updates.

---

Makefile
account_authentications.go
account_authentications_test.go
account_team_invites.go
account_team_invites_test.go
account_team_members.go
account_team_members_test.go
account_team_projects.go
account_team_projects_test.go
account_teams.go
account_teams_test.go
accounts_acc_test.go
accounts_test.go
aiven_go_client_suite_test.go
client.go
client_test.go
elasticsearch_acls_test.go
examples/accounts/main.go
kafka_connector_test.go
kafka_schemas_test.go
project.go
project_test.go

Added support for:
- accounts projects
- accounts authentication 
- account team invites
Also, acceptance tests added for accounts please run ```make testacc```

Add accounts support 2

---

Makefile

add possibility to pass arguments to run specific test if necessary

testacc: add possibility to pass arguments

---

CHANGELOG.md
account_authentications.go
accounts_acc_test.go

account authentication add two new SAML properties: saml_acs_url and saml_metadata_url

Account authentication add two new SAML properties

---

CHANGELOG.md
aiven_go_client_suite_test.go
mirrormaker_replication_flow.go
mirrormaker_replication_flow_acc_test.go
mirrormaker_replication_flow_test.go

fix mirror maker replication flow update
It is not compatible with Aiven API, also acceptance tests were added to validate the whole flow

Replication flow update

---

transit_gateway_vpc_attachment.go
vpc.go
vpc_peering_connection.go

add support for AWS Transit Gateway and support for new Azure API parameters

add support for AWS Transit Gateway

---

client.go

if environment variable `AIVEN_CA_CERT` contains a valid root CA add it to the system pool of certificates

add root ca support

---

kafka_topic.go

This is useful for compatibility with Terraform and Kubernetes

change Kafka topic config float value from float32 to float64

---

kafka_topic.go
kafka_topic_acc_test.go

API retrieves values like 9223372036854776000, which is out of range for int

change kafka topic config int value from int64

---

account_team_projects.go
accounts_acc_test.go

`project_name` field should not be in the PUT request body

fix account team project update method

---

service_user.go

omitmepty includes struct to request, therefore changing type to a pointer

fix service user access control

---

static_ips.go

Adds basic support for Static IPs.

Add StaticIPs handler

---

billing_group_acc_test.go

to validate pls run 
`AIVEN_ACC=1 go test -v -count 1 -parallel 20 -ginkgo.v -ginkgo.progress -ginkgo.focus=Billing --cover -timeout 30m .`

fix billing group acc test

---

Makefile

for example: make testacc FOCUS='BillingGroup'

add possibility to run a single ginkgo test

---

accounts_acc_test.go
examples/accounts/main.go
examples/elasticsearch/main.go
examples/kafka_connectors/main.go
examples/kafka_schemas/main.go
kafka_schemas_acc_test.go
kafka_topic_acc_test.go
mirrormaker_replication_flow_acc_test.go
project_acc_test.go
service_task_acc_test.go

- fix acceptance test with the new API fields
- sort go imports
To validate that pls run `make testacc`

fix acceptance tests

---

flink.go
flink_job.go
flink_table.go

- adds Flink validation endpoints support

add Flink validation endpoints support

---

account_authentications.go

- updates account authentication SAML fields

update account authentication SAML fields

---

account_authentications.go

- adds SAML field mapping public struct
- make `SAMLFieldMapping` a pointer

add SAML field mapping public struct

---

exp/filter.go
exp/filter_test.go
go.mod
go.sum
project.go

adds filtration logic that could be easily integrated for use with various endpoints

add filtration logic

---

azure_privatelink.go
client.go

Terraform can not provide connection id on import.

get AzurePrivatelinkConnectionResponse with optional id

---

service.go

Adds the missing object updates for the maintenances to list the current maintenances of the service

adds the updates inside the service.maintenances object

---

service.go

Adds MySQL params (connection info).

add mysql params

---

project.go
tools/exp/convert/convert.go
tools/exp/diff/diff.go
tools/exp/dist/integration_endpoint_types.yml
tools/exp/dist/integration_types.yml
tools/exp/dist/service_types.yml
tools/exp/types/types.go

adds support for missing `required` property in the generated YAML user config options schema

feat(exp): add required property

---

tools/exp/diff/diff.go
tools/exp/dist/integration_types.yml
tools/exp/dist/service_types.yml

fixes nested required not being generated

fix(exp): nested required not being generated

---

tools/exp/convert/convert.go
tools/exp/types/types.go
tools/exp/util/util.go

fixes incorrect numbers in IEEE 754 mode

fix(exp): incorrect numbers in IEEE 754 mode

---

service.go

Hello,
Some fields were added lately in your API but are still missing here, just adding them :) 
https://api.aiven.io/doc/#tag/Service/operation/ServiceBackupsGet

adds the missing field in the backup object

---

tools/exp/dist/integration_types.yml
tools/exp/dist/service_types.yml

drops deprecated user config options from generated Yaml files

chore(exp): drop deprecated options

---

tools/exp/cmd/root.go

adds an ability to automatically and fully regenerate Yaml files

feat(exp): regeneration flag

---

flink_application.go
flink_application_version.go

adds support for Flink Application

feat(client): flink application support

---

.github/workflows/codeql.yml

fixes branch name in `codeql` workflow

ci(codeql): fix branch name

---

service_integration.go

Missing optional [fields](https://api.aiven.io/doc/#tag/Service_Integrations/operation/ServiceIntegrationCreate)

feat(service_integration): add dest_project, source_project fields

---

accounts.go

feat(account): add parent id

---

.github/workflows/releaser.yml

make releaser to only release on relevant changes
we don't want to have _too_ many releases

ci(releaser): only release on relevant changes

---

billing_group.go

adds support for invoices and invoice lines
resolves #293

feat(billing_group): invoices and invoice lines

---

client.go
client_test.go

- Adds more retry attempts
- Merges outer retry loop with retryablehttp client retries
- Retries 501, 408, 417 and variuose cases

feat: improve retries

---

client.go
opensearch_security_plugin.go

adds security plugin endpoints

feat(opensearch): security plugin endpoints

---

.github/workflows/test.yml

ci(test): fix workflow

---

client.go
opensearch_security_plugin.go

chore(opensearch): port security plugin endpoints to v2

---

client.go
go.sum
project.go
project_organization_groups.go

Add support for Organization Group handler

feat: add project organization handler

---

organization_application_user.go

adds missing `omitempty` fields in organization application user handler

fix(organization_application_user): missing omitempty fields

---

service_integration_endpoint.go

The field is required:
- https://api.aiven.io/doc/#tag/Service_Integrations/operation/ServiceIntegrationEndpointCreate
- https://api.aiven.io/doc/#tag/Service_Integrations/operation/ServiceIntegrationEndpointUpdate

fix(service_integration_endpoint): user_config is required

---

mirrormaker_replication_flow.go
mirrormaker_replication_flow_acc_test.go
util_test.go

fixes incorrect `omitempty` indication in `mirrormaker_replication_flow`

fix(mirrormaker_replication_flow): incorrect omitempty indication

---

organization.go

- Adds Organization Create endpoint support.
- Adds missing fields to the `OrganizationInfo` struct.

feat(organization): create endpoint

---

organization.go

Adds Organization Update endpoint support.

feat(organization): update endpoint

---

service.go

Fixes missing connection info in `service.go`.

fix(service): missing connection info

---

mirrormaker_replication_flow.go

Adds ReplicationFlow `replication_factor`

feat: add replication_factor

---

README.md

Updates readme with Contribution and Deprecation Notice

chore: add contribution notice

---

service.go

* receiver_ingesting_remote_write_uri
* store_uri

fix: remove two thanos connection fields

---

service_user.go

Resolves #374, see https://api.aiven.io/doc/#tag/Service/operation/ServiceUserCreate for supported properties.

chore: add Valkey and Dragonfly ACL keys

---

kafka_topic.go

feat: add kafka topic `diskless_enable`
